let arr = [
    {
        price: 749,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/34788120.jpg",
        name: "Need For Speed Hot Pursuit Remastered для PS4 (Blu-ray диск, Russian version)",
        platform: "PlayStation 4",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        genre: "Автосимулятори (гонки)",
        box: "Blu-ray box",
        developer: "Activision",
        pg: 12,
        publisher: "Activision Blizzard",
        features: "Без мультиплеєра",
        developCountry: "Австрія",
        brendFrom: "Японія",
    },
    {
        price: 1299,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/15723760.jpg",
        name: "Call of Duty: Modern Warfare для PS4 (Blu-ray диск, Russian version)",
        platform: "PlayStation 4",
        localizetion: "Російська версія",
        release: "25 жовтня 2019 р.",
        discType: "Blu-ray",
        releaseUkr: "25 жовтня 2019 р.",
        genre: "Шутер від першої особи (FPS)",
        systemRequirements:
            "platform PlayStation 4 За наявності багатокористувацького мережевого режиму гри через інтернет потрібна передплата PlayStation Plus (купується окремо) і під'єднання ігрової консолі до мережі інтернет",
        box: "Blu-ray box",
        developer: "Infinity Ward",
        pg: 18,
        publisher: "Activision",
        features: "З мультиплеєром",
        developCountry: "Австрія",
        brendFrom: "США Японія",
    },
    {
        price: 1999,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/26382530.jpg",
        name: "Bandicoot 4: It's About Time для PS4 (Blu-ray диск, Russian subtitles)",
        platform: "PlayStation 4",
        localizetion: "З російськими субтитрами",
        release: "2 жовтня 2020 року",
        discType: "Blu-ray",
        releaseUkr: "2 жовтня 2020 року",
        genre: "Пригоди (adventure)",
        systemRequirements:
            "platform PlayStation 4 За наявності багатокористувацького мережевого режиму гри через Інтернет потрібна передплата PlayStation Plus (купується окремо) і під'єднання ігрової консолі до мережі Інтернет.",
        box: "Blu-ray box",
        developer: "Activision",
        pg: 6,
        publisher: "Activision",
        features: "Без мультиплеєра",
        developCountry: "Австрія",
        brendFrom: "Австрія",
    },
    {
        price: 699,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/216849487.png",
        name: "Характеристики Sony Playstation 4 Tony Hawk's Pro Skater 1+2 PS4 (88473EN)",
        platform: "PlayStation 4",
        localizetion: "Англійська версія",
        discType: "Blu-ray",
        playersNum: "2",
        genre: "Action Симулятор",
        Guarantee: "14 днів",
    },
    {
        price: 1219,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/33422654.jpg",
        name: "Характеристики Spyro Reignited Trilogy (англійська версія) PS4",
        platform: "PlayStation 4",
        localizetion: "Англійська версія",
        pg: 7,
    },
    {
        price: 6,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/264516412.jpg",
        name: "Destiny 2 на PS4 (Blu-Ray диск, російська версія)",
        platform: "PlayStation 4",
        localizetion: "Російська версія",
        release: "6 сентября 2017",
        discType: "Blu-ray",
        releaseUkr: "6 сентября 2017",
        playersNum: "1",
        genre: "Action Рольові (RPG)",
        systemRequirements: "platform Playstation 4",
        box: "box",
        servicActiv: "Не вимагає активації",
        developer: "Bungie",
        pg: 16,
        publisher: "Activision",
        developCountry: "США",
    },
    {
        price: 2599,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/270827040.jpg",
        name: "Call of Duty: Modern Warfare II для PS5 (Blu-ray диск, Russian version)",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        release: "28.11.2022",
        discType: "Blu-ray",
        genre: "Шутер від першої особи (FPS)",
        systemRequirements:
            "platform PlayStation 5 При наличии многопользовательского сетевого режима игры через Интернет, потребуется подписка PlayStation Plus (приобретается отдельно) и подключение игровой консоли к сети Интернет.",
        box: "Blu-ray box",
        developer: "Infinity Ward",
        pg: 18,
        publisher: "Activision",
        features: "З мультиплеєром",
        developCountry: "Австрія",
        brendFrom: "США Японія",
    },
    {
        price: 2199,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/215745339.jpg",
        name: "Call of Duty: Vanguard для PS5 (Blu-ray-диск, Russian version)",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        release: "5 листопада 2021",
        discType: "Blu-ray",
        genre: "Шутер від першої особи (FPS)",
        box: "Blu-ray box",
        developer: "Infinity Ward",
        pg: 18,
        publisher: "Activision",
        features: "З мультиплеєром",
        developCountry: "Австрія",
        brendFrom: "США Японія",
    },
    {
        price: 899,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/167269490.png",
        name: "Call of Duty: Black Ops Cold War PS5 (88505UR)",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        playersNum: "1",
        Guarantee: "14 днів",
    },
    {
        price: 399,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/177006663.jpg",
        name: "Call of Duty: Black Ops для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "09 ноября 2010",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows® Vista/XP/7, Процессор: Intel® Core2 Duo E6600 или AMD Phenom X3 8750 или лучше, ОЗУ: 2 ГБ, Видеокарта: с 256 МБ, NVIDIA® GeForce® 8600GT / ATI Radeon® X1950Pro или лучше, Жесткий диск: 12 ГБ, Звуковая карта: совместимая с DirectX® 9.0c",
        genre: "Action",
        developer: "Treyarch",
        features: "З мультиплеєром",
    },
    {
        price: 399,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/6932597.jpg",
        name: "Call of Duty 2 для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Англійська версія",
        release: "25 октября 2005",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows 2000/XP, Процессор: Pentium 4 1.4 GHz, Оперативная память: 256 Mb, Место на диске: 4 Gb",
        genre: "Action",
        systemRequirements:
            "ОС: Windows 2000/XP, Процессор: Pentium 4 3.2 GHz, Оперативная память: 1 Gb, Место на диске: 4 Gb HD space",
        servicActiv: "Steam",
        developer: "Infinity Ward",
        features: "З мультиплеєром",
    },
    {
        price: 136,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/6930674.jpg",
        name: "Geometry Wars 3: Dimensions Evolved для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Англійська версія",
        release: "25 ноября 2014",
        discType: "Електронний ключ",
        minRequireSis:
            "Минимальные системны требования:ОС: Windows 7, Процессор: Intel Core 2 Duo/AMD Athlon 64 X2 3800+, Оперативаня память: 2 GB ОЗУ, Видеокарта: NVIDIA GeForce 6800 GT 512MB/ATI Radeon X1900XT 512MB, Место на диске: 1 GB",
        genre: "Action",
        servicActiv: "Steam",
        developer: "Lucid Games",
    },
    {
        price: 449,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/6938964.jpg",
        name: "Call of Duty: Modern Warfare 2 для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "12 ноября 2009",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows XP/Vista/7, Процессор: Intel Pentium 4 3.2 GHz/AMD Athlon 64 3200+, Оперативная память: 1 GB, Видеокарта: NVIDIA GeForce 6600GT/ATI Radeon 1600XT, Место на диске: 12 GB",
        genre: "Action",
        servicActiv: "Steam",
        developer: "Infinity Ward",
        features: "З мультиплеєром",
    },
    {
        price: 129,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/19980639.jpg",
        name: "Характеристики Spyro Reignited Trilogy (Switch)",
        platform: "Nintendo Switch",
        localizetion: "Англійська версія",
        genre: "Дитячі",
        publisher: "Activision",
    },
    {
        price: 129,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/19980639.jpg",
        name: "Характеристики Spyro Reignited Trilogy (Switch)",
        platform: "Nintendo Switch",
        localizetion: "Англійська версія",
        genre: "Дитячі",
        publisher: "Activision",
    },
    {
        price: 545,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/287363303.jpg",
        name: "Характеристики Ключ активації Call of Duty: Ghosts Gold для XBOX ONE / Series X|S",
        platform: "Xbox One Xbox Series",
        discType: "Електронний ключ",
        genre: "Action Аркади (Arcade)",
        developer: "Infinity Ward",
        publisher: "Activision",
    },
    {
        price: 219,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/264926692.jpg",
        name: "Характеристики Call of Duty Vanguard (Xbox One, російська версія)",
        platform: "Xbox One Xbox Series",
        localizetion: "Російська версія",
        genre: "Шутер від першої особи (FPS)",
        publisher: "Activision",
    },
    {
        price: 129,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/264926692.jpg",
        name: "Характеристики Spyro Reignited Trilogy (Xbox One)",
        platform: "Xbox One Xbox Series",
        localizetion: "Англійська версія",
        genre: "Дитячі",
        developer: "Toys For Bob",
        publisher: "Activision",
    },
    {
        price: 1299,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/27436381.jpg",
        name: "UFC 4 для PS4 (Blu-ray диск, Russian version)",
        platform: "PlayStation 4",
        localizetion: "З російськими субтитрами",
        release: "14 серпня 2020 року",
        discType: "Blu-ray",
        releaseUkr: "14 серпня 2020 року",
        genre: "Військові (fighting)",
        systemRequirements:
            "platform PlayStation 4 За наявності багатокористувацького мережевого режиму гри через Інтернет, потрібна передплата PlayStation Plus (купується окремо) і під'єднання ігрової консолі до мережі Інтернет.",
        box: "Blu-ray box",
        developer: "EA Sports",
        publisher: "Electronic Arts",
        features: "З мультиплеєром",
        developCountry: "Австрія",
        brendFrom: "Японія",
    },
    {
        price: 2349,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/281938048.png",
        name: "Характеристики Игра Sony PlayStation 4 FIFA 23 PS4 Русская Озвучка",
        platform: "PlayStation 4",
        playersNum: "4",
        genre: "Спортивні (sport)",
        pg: 3,
    },
    {
        price: 899,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/201659656.png",
        name: "для PS4 FIFA 22 (1081387)",
        platform: "PlayStation 4 PlayStation 5",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        playersNum: "4",
        genre: "Симулятор Спортивні (sport)",
        Guarantee: "14 днів",
    },
    {
        price: 17,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/235006633.jpg",
        name: "Характеристики Battlefield 2042 PS4 (російська версія)",
        platform: "PlayStation 4",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        genre: "Шутер від першої особи (FPS)",
        box: "Blu-ray box",
        developer: "EA DICE",
        publisher: "Electronic Arts",
        features: "З мультиплеєром",
    },
    {
        price: 19,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/270002307.jpg",
        name: "Характеристики Star Wars Battlefront II (PS4, російські субтитри)",
        platform: "PlayStation 4",
        localizetion: "З російськими субтитрами",
        genre: "Шутер від першої особи (FPS)",
        publisher: "Crytek",
    },
    {
        price: 999,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/272732665.jpg",
        name: "Характеристики Star Wars Jedi: Fallen Order PS4 (русская версия)",
        platform: "PlayStation 4",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        genre: "Action Пригоди (adventure)",
        box: "Blu-ray box",
        developer: "Respawn Entertainment",
        publisher: "Electronic Arts",
        features: "Без мультиплеєра",
    },
    {
        price: 68,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/19117996.jpg",
        name: "Характеристики Mirrors Edge Catalyst (PS4, російська версія)",
        platform: "PlayStation 4",
        localizetion: "Російська версія",
        genre: "Пригоди (adventure)",
        publisher: "Electronic Arts",
    },
    {
        price: 85,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/19117990.jpg",
        name: "Характеристики Plants vs Zombies Garden Warfare (PS4)",
        platform: "PlayStation 4",
        localizetion: "Англійська версія",
        genre: "Шутер від першої особи (FPS)",
        publisher: "Electronic Arts",
    },
    {
        price: 2999,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/279559431.jpg",
        name: "FIFA 23 для PS5 (Blu-ray диск)",
        platform: "PlayStation 5",
        localizetion: "Англійська версія Російська версія",
        discType: "Blu-ray",
        minRequireSis:
            "platform PlayStation 5 При наличии многопользовательского сетевого режима игры через Интернет, потребуется подписка PlayStation Plus (приобретается отдельно) и подключение игровой консоли к сети Интернет.",
        genre: "Спортивні (sport)",
        developer: "EA Canada",
        pg: 0,
        publisher: "Electronic Arts",
        features: "З мультиплеєром",
        developCountry: "Австрія",
        brendFrom: "США",
    },
    {
        price: 199,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/241808344.jpg",
        name: "Grid Legends для PS5 (Blu-ray-диск, Russian version)",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        release: "25 лютого 2022 р.",
        discType: "Blu-ray",
        releaseUkr: "25 лютого 2022 р.",
        playersNum: "5 і більше",
        genre: "Action Автосимулятори (гонки) Симулятор Спортивні (sport)",
        systemRequirements:
            "platform PlayStation 5 Для мережевої багатокористувацької гри потрібна передплата PlayStation Plus (купується окремо) і під'єднання ігрової консолі до мережі Інтернет.",
        box: "Blu-ray box",
        developer: "Codemasters",
        pg: 6,
        publisher: "Electronic Arts",
        features: "З мультиплеєром",
        developCountry: "США",
        brendFrom: "Великобританія",
    },
    {
        price: 2429,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/298089895.png",
        name: "Характеристики Грати Sony PlayStation 5 Need for Speed ​​Unbound Російські Субтитри",
        platform: "PlayStation 5",
        localizetion: "З російськими субтитрами",
        discType: "Blu-ray",
        playersNum: "1",
        genre: "Автосимулятори (гонки)",
        Guarantee: "14 днів",
    },
    {
        price: 1699,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/185582789.jpg",
        name: "F1 2021 для PS5 (Blu-ray-диск, Russian subtitles)",
        platform: "PlayStation 5",
        localizetion: "З російськими субтитрами",
        release: "16 липня 2021 г",
        discType: "Blu-ray",
        releaseUkr: "16 липня 2021 г",
        genre: "Автосимулятори (гонки)",
        systemRequirements:
            "platform PlayStation 5 За наявності багатокористувацького мережевого режиму гри через Інтернет, потрібна передплата PlayStation Plus (купується окремо) і під'єднання ігрової консолі до мережі Інтернет.",
        developer: "Codemasters",
        pg: 6,
        publisher: "Electronic Arts",
        features: "З мультиплеєром",
        developCountry: "США",
        brendFrom: "США",
    },
    {
        price: 1399,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/273464260.jpg",
        name: "NHL 22 для PS5 (Blu-ray диск, Russian subtitles)",
        platform: "PlayStation 5",
        distributorInUkraine: "ERC",
        localizetion: "З російськими субтитрами",
        discType: "Blu-ray",
        releaseUkr: "2021",
        playersNum: "4",
        genre: "Симулятор Спортивні (sport)",
        systemRequirements:
            "За наявності багатокористувацького мережевого режиму гри через Інтернет, потрібна передплата PlayStation Plus (купується окремо) і під'єднання ігрової консолі до мережі Інтернет.",
        box: "Blu-ray box",
        developer: "EA Vancouver",
        pg: 12,
        publisher: "Electronic Arts",
        features: "З мультиплеєром",
        developCountry: "Австрія",
        Guarantee: "14 днів",
    },
    {
        price: 1469,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/15870102.jpg",
        name: "FIFA 20. Стандартное издание для Xbox One (Blu-ray диск, Russian version)",
        platform: "Xbox One",
        localizetion: "Російська версія",
        release: "27 вересня 2019 року",
        discType: "Blu-ray",
        releaseUkr: "27 вересня 2019 року",
        genre: "Спортивні (sport)",
        systemRequirements:
            "platform Xbox One Гравців через мережу: 1-22 Гравців поза мережею: 1-4 За наявності багатокористувацького мережевого режиму гри через Інтернет потрібний золотий статус Xbox Live Gold (купується окремо) і під'єднання ігрової консолі до мережі Інтернет",
        box: "Blu-ray box",
        developer: "Electronic Arts",
        pg: 0,
        publisher: "Electronic Arts",
        features: "З мультиплеєром",
        developCountry: "Австрія",
        brendFrom: "США Японія",
    },
    {
        price: 1699,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/29920359.jpg",
        name: "Need For Speed. Heat для Xbox One (Blu-ray диск, Russian version)",
        platform: "Xbox One",
        localizetion: "Російська версія",
        release: "8 листопада 2019 р.",
        discType: "Blu-ray",
        releaseUkr: "8 листопада 2019 р.",
        minRequireSis:
            "platform Xbox One За наявності багатокористувацького мережевого режиму гри через Інтернет, необхідний золотий статус Xbox Live Gold (купується окремо) і під'єднання ігрової консолі до мережі Інтернет.",
        genre: "Автосимулятори (гонки)",
        box: "Blu-ray box",
        developer: "Ghost Games",
        pg: 12,
        publisher: "Electronic Arts",
        features: "З мультиплеєром",
        developCountry: "Австрія",
        brendFrom: "Японія",
    },
    {
        price: 1899,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/150510543.jpg",
        name: "FIFA 21 для Xbox One, безкоштовне оновлення до версії Xbox Series X (Blu-ray диск, Russian version)",
        platform: "Xbox One",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        genre: "Спортивні (sport)",
        systemRequirements:
            "platform Xbox One За наявності багатокористувацького мережевого режиму гри через Інтернет потрібний золотий статус Xbox Live Gold (купується окремо) і під'єднання ігрової консолі до мережі Інтернет",
        box: "Blu-ray box",
        developer: "Electronic Arts",
        pg: 0,
        publisher: "Electronic Arts",
        features: "З мультиплеєром",
        developCountry: "Австрія",
        brendFrom: "Австрія",
    },
    {
        price: 749,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/276749111.jpg",
        name: "Характеристики Need For Speed ​​Hot Pursuit Remastered XBox One (російські субтитри)",
        platform: "Xbox One Xbox Series",
        localizetion: "З російськими субтитрами",
        discType: "Blu-ray",
        genre: "Автосимулятори (гонки)",
        box: "Blu-ray box",
        developer: "Criterion Games",
        publisher: "Electronic Arts",
        features: "З мультиплеєром",
    },
    {
        price: 49,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/287363604.jpg",
        name: "Характеристики Ключ активації Need for Speed ​​Rivals для XBOX ONE / Series X|S",
        platform: "Xbox One Xbox Series",
        discType: "Електронний ключ",
        genre: "Action Пригоди (adventure)",
        developer: "Ghost Games",
        publisher: "Electronic Arts",
    },
    {
        price: 143,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/22551615.jpg",
        name: "Характеристики Star Wars Jedi Fallen Order (Xbox One, російська версія)",
        platform: "Xbox One Xbox Series",
        localizetion: "Російська версія",
        genre: "Пригоди (adventure)",
        publisher: "Electronic Arts",
    },
    {
        price: 1169,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/246741513.jpg",
        name: "Характеристики GTA 5 Premium Edition PS4 (російські субтитри)",
        platform: "PlayStation 4",
        localizetion: "З російськими субтитрами",
        discType: "Blu-ray",
        genre: "Action Пригоди (adventure)",
        box: "Blu-ray box",
        developer: "Rockstar North",
        publisher: "Rockstar Games",
        features: "З відкритим світом З мультиплеєром",
    },
    {
        price: 1399,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/272732216.jpg",
        name: "Характеристики Red Dead Redemption 2 PS4 (російські субтитри)",
        platform: "PlayStation 4",
        localizetion: "З російськими субтитрами",
        discType: "Blu-ray",
        genre: "Пригоди (adventure) Шутер від першої особи (FPS) Шутер від третьої особи (TPS)",
        box: "Blu-ray box",
        developer: "Rockstar Games",
        publisher: "Rockstar Games",
        features: "З мультиплеєром",
    },
    {
        price: 1399,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/293029164.jpg",
        name: "Характеристики GTA 5 PS5 (російські субтитри)",
        platform: "PlayStation 5",
        localizetion: "З російськими субтитрами",
        discType: "Blu-ray",
        genre: "Action Пригоди (adventure)",
        box: "Blu-ray box",
        developer: "Rockstar Games",
        publisher: "Rockstar Games",
        features: "З відкритим світом З мультиплеєром",
    },
    {
        price: 479,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/6942926.jpg",
        name: "Grand Theft Auto V (GTA V): Premium Online Edition для ПК (Ключ активації Rockstar Games)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "14 апреля 2015",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows 8.1, Windows 8, Windows 7 (SP1) x64, Процессор: Intel Core 2 Q6600 @ 2.40 ГГц/AMD Phenom 9850 @ 2.5 ГГц, Оперативная память: 4ГБ, Видеокарта: NVIDIA 9800 GT, 1ГБ/AMD HD 4870, 1ГБ, Место на диске: не менее 72ГБ",
        genre: "Action Пригоди (adventure)",
        systemRequirements:
            "ОС: Windows 8.1, Windows 8, Windows 7 (SP1) x64, Процессор: Intel Core i5 3470/AMD X8 FX-8350 @, Оперативная память: 8ГБ, Видеокарта: NVIDIA GTX 660, 2ГБ/AMD HD7870, 2ГБ, Место на диске: не менее 72ГБ",
        developer: "Rockstar North",
        publisher: "Rockstar Games",
        features: "З мультиплеєром",
    },
    {
        price: 299,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/6940721.jpg",
        name: "Max Payne 3 для ПК (Ключ активації Rockstar Games)",
        platform: "Mac OS PC",
        localizetion: "Російська версія",
        release: "01 июня 2012",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows 7 SP1, Windows Vista SP2, Windows XP SP3, Процессор: Intel Core 2 Duo 2,4GHz, Оперативная память: 2,4GHz, Видеокарта: NVIDIA 8600 GT 512MB/Radeon HD 3400 512MB, Место на диске: 35 GB",
        genre: "Action",
        servicActiv: "Steam",
        developer: "Rockstar North",
        publisher: "Rockstar Games",
        features: "З мультиплеєром",
    },
    {
        price: 199,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/6943713.jpg",
        name: "Bully: Scholarship Edition для ПК (Ключ активації Rockstar Games)",
        platform: "PC",
        localizetion: "Англійська версія",
        release: "21 октября 2008",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows XP/Windows Vista, Процессор: Intel Pentium 4 (с тактовая частота 3 ГГц)/AMD Athlon 3000+, Оперативная память: 1ГБ, Видеокарта: Nvidia 6800 или 7300 или лучше, ATI Radeon X1300 oили лучше, Место на диске: 4,7ГБ",
        genre: "Action Пригоди (adventure)",
        servicActiv: "Steam",
        developer: "Rockstar Games",
        features: "Без мультиплеєра",
    },
    {
        price: 699,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/268517419.jpg",
        name: "Характеристики Assassin's Creed: Odyssey Deluxe Edition (Ubisoft)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "01.10.2018",
        discType: "Електронний ключ",
        releaseUkr: "01.10.2018",
        playersNum: "1",
        servicActiv: "Ubisoft Connect",
        developer: "Ubisoft Quebec",
        pg: 18,
        publisher: "Ubisoft Entertainment",
        features: "З відкритим світом",
    },
    {
        price: 399,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/248270679.jpg",
        name: "Характеристики Watch Dogs 2 Standard Edition (Ubisoft)",
        platform: "PC",
        distributorInUkraine: "Бука",
        localizetion: "Російська версія",
        release: "29.11.2016",
        discType: "Електронний ключ",
        releaseUkr: "29.11.2016",
        servicActiv: "Ubisoft Connect",
        pg: 18,
        publisher: "Ubisoft Entertainment",
        features: "З відкритим світом З мультиплеєром",
    },
    {
        price: 2299,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/226725826.jpg",
        name: "Far Cry 6 для PS4 (Blu-ray-диск, Russian version)",
        platform: "PlayStation 4",
        localizetion: "Російська версія",
        release: "7 жовтня 2021 року",
        discType: "Blu-ray",
        genre: "Пригоди (adventure) Шутер від першої особи (FPS)",
        systemRequirements:
            "platform PlayStation 4 За наявності багатокористувацького мережевого режиму гри через Інтернет потрібна передплата PlayStation Plus (купується окремо) і під'єднання ігрової консолі до мережі Інтернет.",
        box: "Blu-ray box",
        developer: "Ubisoft Entertainment",
        pg: 18,
        publisher: "Ubisoft Entertainment",
        features: "З мультиплеєром",
        developCountry: "Австрія",
        brendFrom: "Франція",
    },
    {
        price: 749,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/302194293.jpg",
        name: "Rayman Legends - Хиты PlayStation для PS4 (Blu-ray диск, Russian version)",
        platform: "PlayStation 4",
        localizetion: "Російська версія",
        release: "10.08.2018",
        discType: "Blu-ray",
        genre: "Пригоди (adventure)",
        box: "Case Set",
        developer: "Ubisoft Montreal",
        publisher: "Ubisoft Entertainment",
        features: "З мультиплеєром",
        developCountry: "Австрія",
        brendFrom: "США",
    },
    {
        price: 1485,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/281693257.jpg",
        name: "Far Cry 4 (Russian version) + Far Cry 5 (English version) для PS4 (2in1, Blu-ray диски)",
        platform: "PlayStation 4 PlayStation 5",
        distributorInUkraine: "ERC",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        releaseUkr: "2014 , 2018",
        playersNum: "1",
        genre: "Action Пригоди (adventure) Шутер від першої особи (FPS)",
        systemRequirements:
            "За наявності багатокористувацького мережевого режиму гри через Інтернет, потрібна підписка PlayStation Plus (купується окремо) і підключення ігрової консолі до мережі Інтернет.",
        box: "Blu-ray box",
        developer: "Ubisoft",
        pg: 18,
        publisher: "Ubisoft Entertainment",
        features: "З відкритим світом",
        developCountry: "Австрія",
        Guarantee: "14 днів",
    },
    {
        price: 122,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/281693257.jpg",
        name: "Характеристики Tom Clancy's Ghost Recon: Breakpoint PS4 (російські субтитри)",
        platform: "PlayStation 4",
        localizetion: "З російськими субтитрами",
        discType: "Blu-ray",
        genre: "Шутер від першої особи (FPS)",
        box: "Blu-ray box",
        developer: "Ubisoft Entertainment",
        publisher: "Ubisoft Entertainment",
        features: "З відкритим світом З мультиплеєром",
    },
    {
        price: 1799,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/252177532.jpg",
        name: "Riders Republic. Freeride Edition для PS5 (Blu-ray-диск, Russian version)",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        genre: "Action",
        systemRequirements:
            "За наявності багатокористувацького мережевого режиму гри через Інтернет, потрібна передплата PlayStation Plus (купується окремо) і під'єднання ігрової консолі до мережі Інтернет.",
        box: "Blu-ray box",
        developer: "Ubisoft Entertainment",
        pg: 12,
        publisher: "Ubisoft Entertainment",
        features: "З мультиплеєром",
        developCountry: "Австрія",
        brendFrom: "Франція",
    },
    {
        price: 18,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/294377983.jpg",
        name: "Stray на PS5 (Blu-Ray-диск, російські субтитри)",
        platform: "PlayStation 5",
        localizetion: "Англійська версія З російськими субтитрами",
    },
    {
        price: 199,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/225700602.jpg",
        name: "Характеристики Watch Dogs: Legion Resistance Edition (російська версія)",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        genre: "Action Шутер від третьої особи (TPS)",
        box: "Blu-ray box",
        developer: "Ubisoft Entertainment",
        publisher: "Ubisoft Entertainment",
    },
    {
        price: 779,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/299998714.jpg",
        name: "Характеристики Assassin's Creed Valhalla\\Вальгалла (ваучер на скачування) (російська версія) (Xbox One | Series X)",
        platform: "Xbox One Xbox Series",
        genre: "Action",
    },
    {
        price: 799,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/276749083.jpg",
        name: "Характеристики Far Cry 6 XBox One (англійська версія)",
        platform: "Xbox One Xbox Series",
        localizetion: "Англійська версія",
        discType: "Blu-ray",
        genre: "Шутер від першої особи (FPS)",
        box: "Blu-ray box",
        developer: "Ubisoft Toronto",
        publisher: "Ubisoft Entertainment",
        features: "З відкритим світом",
    },
    {
        price: 1299,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/163153781.jpg",
        name: "Demon's Souls для PS5 (Blu-ray диск, Russian version)",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        genre: "Жахи, виживання (survival horror)",
        box: "Blu-ray box",
        developer: "Bluepoint Games",
        pg: 18,
        publisher: "SIE (Sony Interactive Entertainment)",
        features: "Без мультиплеєра",
        developCountry: "Австрія",
        brendFrom: "Японія",
    },
    {
        price: 1599,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/47140378.jpg",
        name: "Hitman 3 для PS5 (Blu-Ray диск, Russian subtitles)",
        platform: "PlayStation 5",
        localizetion: "З російськими субтитрами",
        release: "20 січня 2021 р.",
        discType: "Blu-ray",
        releaseUkr: "20 січня 2021 р.",
        playersNum: "1",
        genre: "Action",
        systemRequirements:
            "platform PlayStation 5 За наявності багатокористувацького мережевого режиму гри через Інтернет, потрібна передплата PlayStation Plus (купується окремо) і під'єднання ігрової консолі до мережі Інтернет.",
        developer: "IO Interactive",
        pg: 18,
        publisher: "Square Enix",
        features: "З підтримкою VR",
        developCountry: "Австрія",
        brendFrom: "США",
    },
    {
        price: 1899,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/304533164.jpg",
        name: "Mortal Kombat 11 Ultimate Edition для PS5 (Blu-ray диск, Russian version)",
        platform: "PlayStation 5",
        discType: "Blu-ray",
        genre: "Військові (fighting)",
        box: "Blu-ray box",
        developer: "NetherRealm Studios",
        publisher: "Warner Bros. Games",
        features: "З мультиплеєром",
        developCountry: "Австрія",
        brendFrom: "Японія",
    },
    {
        price: 1899,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/184872722.jpg",
        name: "Final Fantasy VII Remake для PS5 (Blu-ray-диск, English version)",
        platform: "PlayStation 5",
        localizetion: "З російською документацією",
        discType: "Blu-ray",
        genre: "Рольові (RPG)",
        systemRequirements:
            "platform PlayStation 5 За наявності багатокористувацького мережевого режиму гри через Інтернет, потрібна передплата PlayStation Plus (купується окремо) і під'єднання ігрової консолі до мережі Інтернет.",
        box: "Blu-ray box",
        developer: "Square Enix",
        publisher: "Square Enix",
        features: "Без мультиплеєра",
        developCountry: "Австрія",
        brendFrom: "Австрія",
    },
    {
        price: 2299,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/252074523.jpg",
        name: "Dying Light 2 Stay Human для PS5 (Blu-ray-диск, Russian version) (5902385108188)",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        release: "4 лютого 2022",
        discType: "Blu-ray",
        releaseUkr: "4 лютого 2022",
        playersNum: "4",
        genre: "Action Рольові (RPG)",
        box: "Blu-ray box",
        developer: "Techland",
        publisher: "Бука",
        features: "З мультиплеєром",
    },
    {
        price: 1729,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/231820580.jpg",
        name: "Back 4 Blood Спеціальне видання для PS5 (Blu-ray-диск, English version)",
        platform: "PlayStation 5",
        localizetion: "Англійська версія",
        discType: "Blu-ray",
        genre: "Action Шутер від третьої особи (TPS)",
        box: "Blu-ray box",
        publisher: "Ubisoft Entertainment",
        developCountry: "США",
        brendFrom: "США",
    },
    {
        price: 1989,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/301355254.jpg",
        name: "Характеристики Sonic Frontiers (російська версія) (PS5)",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        discType: "CD",
        playersNum: "1",
        genre: "Action",
        pg: 7,
    },
    {
        price: 149,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/264808380.jpg",
        name: "Характеристики Spider-Man Miles Morales (PS5, російська версія)",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        genre: "Пригоди (adventure)",
        developer: "Marvel",
    },
    {
        price: 849,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/234051572.png",
        name: "Sony Uncharted: Legacy of Thieves Collection PlayStation 5 Російська Озвучка Новий",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        playersNum: "1",
        genre: "Пригоди (adventure)",
        Guarantee: "14 днів",
    },
    {
        price: 1799,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/282358843.jpg",
        name: "Характеристики Ghostwire: Tokyo PS5 (російська версія)",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        genre: "Action Пригоди (adventure)",
        box: "Blu-ray box",
        developer: "Tango Gameworks",
        publisher: "Bethesda Softworks",
        features: "Без мультиплеєра",
    },
    {
        price: 1299,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/263800978.png",
        name: "Resident Evil 8: Village Російська Версія Sony PlayStation 5",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        genre: "Жахи, виживання (survival horror)",
        Guarantee: "14 днів",
    },
    {
        price: 1999,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/297011489.png",
        name: "Характеристики Грати Sony PlayStation 5 No Man's Sky Російська Озвучка",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        playersNum: "1",
        genre: "Action Пригоди (adventure)",
        Guarantee: "14 днів",
    },
    {
        price: 2749,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/302284083.jpg",
        name: "Характеристики God of War: Ragnarok PS5 (російська версія)",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        discType: "Blu-ray",
        genre: "Action Військові (fighting) Пригоди (adventure)",
        box: "Blu-ray box",
        developer: "Santa Monica Studio",
        publisher: "SIE (Sony Interactive Entertainment)",
        features: "Без мультиплеєра",
    },
    {
        price: 1528,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/297898002.jpg",
        name: "Farming Simulator 22 для PS5 (Blu-ray-диск, Russian version)",
        platform: "PlayStation 5",
        localizetion: "Російська версія",
        release: "2021",
        discType: "Blu-ray",
        playersNum: "5 і більше",
        genre: "Симулятор",
        box: "Blu-ray box",
        developer: "Giants Software",
        pg: 3,
        publisher: "Giants Software",
        features: "З мультиплеєром",
        developCountry: "Австрія",
        brendFrom: "Австрія",
    },
    {
        price: 1499,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/287432701.png",
        name: "Характеристики Игра GSC Game World S.T.A.L.K.E.R.: Чистое Небо Collector's Edition Русская Озвучка",
        platform: "PC",
        release: "2008",
        genre: "Шутер від першої особи (FPS)",
        pg: 18,
        publisher: "GSC Game World",
        Guarantee: "14 днів",
    },
    {
        price: 549,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/6930780.jpg",
        name: "The Witcher 3: Wild Hunt – GOTY для ПК (Ключ активації GOG)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "30 августа 2016",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows 7 64bit , Windows 8 (8.1) 64bit, Windows 10 64bit, Процессор: Intel CPU Core i5-2500K 3.3GHz/AMD CPU Phenom II X4 940, Оперативная память: 6 GB, Видеокарта: NVIDIA GPU GeForce GTX 660/AMD GPU Radeon HD 7870, Место на диске: 35 GB",
        genre: "Пригоди (adventure) Рольові (RPG)",
        systemRequirements:
            "ОС: Windows 7 64bit , Windows 8 (8.1) 64bit, Windows 10 64bit, Процессор: Intel CPU Core i7 3770 3.4 GHz/AMD CPU AMD FX-8350 4 GHz, Оперативная память: 8 GB, Видеокарта: NVIDIA GPU GeForce GTX 770/AMD GPU Radeon R9 290, Место на диске: 35 GB",
        servicActiv: "GOG",
        developer: "CD Projekt Red",
        features: "З відкритим світом",
    },
    {
        price: 199,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/174952054.jpg",
        name: "S.T.A.L.K.E.R.: Shadow of Chernobyl для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "20 марта 2007",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows XP (пакет обновления 2)/Microsoft Windows 2000 SP4, Процессор: Intel Pentium 4 2 Ггц/AMD XP 2200+, Видеокарта: совместимая с DirectX® 9c карта 128 МБ, Оперативная память: 512 МБ ОЗУ, Место на диске: 10 ГБ",
        genre: "Action Рольові (RPG)",
        systemRequirements:
            "ОС: Windows XP (пакет обновления 2)/Microsoft Windows 2000 SP4, Процессор: Intel Core 2 Duo E6400/AMD Athlon 64 X2 4200+, Видеокарта: 256мб, Оперативная память: 1 ГБ ОЗУ или лучше, Место на диске: 10 ГБ",
        developer: "GSC Game World",
        features: "З мультиплеєром",
    },
    {
        price: 849,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/6941959.jpg",
        name: "Характеристики Доповнення The Sims 4 – Cats and Dogs для ПК (Ключ активації EA/Origin)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "10 ноября 2017",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows 7 SP1/8/8.1/10 x64, Процессор:Intel Core 2 Duo, AMD Athlon 64 Dual-Core 4000+, Оперативная память: не менее 4ГБ, Видеокарта: 128 Мб с поддержкой пиксельных шейдеров. Видеокарта: NVIDIA GeForce 6600 или лучше, Место на диске: не менее 15ГБ",
        genre: "Симулятор",
        systemRequirements:
            "ОС: Windows 7/8/8.1/10 x64, Процессор: Intel Core i5 или быстрее, AMD Athlon X4, Оперативная память: не менее 4ГБ, Видеокарта: NVIDIA GTX 650 или лучше, Место на диске: 18ГБ",
        servicActiv: "Origin",
        developer: "The Sims Studio",
    },
    {
        price: 649,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/6938472.jpg",
        name: "Detroit: Become Human для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "18 июня 2020",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows 10, 64-bit, Процессор: Intel Core i5-2300 2.8 GHz или AMD Ryzen 3 1200 3.1GHz или AMD FX-8350 4.2GHz, Оперативная память: 8 GB, Видеокарта: Nvidia GeForce GTX 780 или AMD HD 7950 with 3GB (Support of Vulkan 1.1 required), Место на диске: 55 GB",
        genre: "Action Пригоди (adventure)",
        systemRequirements:
            "ОС: Windows 10, 64-bit, Процессор: Intel Core i5-6600 3.3 GHz или AMD Ryzen 3 1300 X 3.4 GHz, Оперативная память: 12 GB, Видеокарта: Nvidia GeForce GTX 1060 или AMD Radeon RX 580 with 4GB (Support of Vulkan 1.1 required), Место на диске: 55 GB",
        servicActiv: "Steam",
        developer: "Quantic Dream",
    },
    {
        price: 149,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/6938720.jpg",
        name: "DiRT Rally для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "07 декабря 2015",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows 7, Windows 8, Windows 10 64bit, Процессор: AMD FX/Intel Core i3, Оперативная память: 4 GB, Видеокарта: С поддержкой DirectX 11, AMD HD5450/NVIDIA GT430/Intel HD4000 1GB, Место на диске: 50 GB",
        genre: "Автосимулятори (гонки) Симулятор Спортивні (sport)",
        systemRequirements:
            "ОС: Windows 7, Windows 8, Windows 10 64bit, Процессор: AMD FX-8150/Intel Core i5 4670K, Оперативная память: 8 GB, Видеокарта: AMD R9 290/NVIDIA GTX 780, Место на диске: 50 GB",
        servicActiv: "Steam",
        developer: "Codemasters",
    },
    {
        price: 849,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/269534225.jpg",
        name: "Minecraft Java + Bedrock Edition для ПК (Ключ активації Microsoft)",
        platform: "Mac OS PC",
        localizetion: "Російська версія",
        release: "18 нояб. 2011г.",
        discType: "Електронний ключ",
        genre: "Action Симулятор",
        developer: "Markus Persson",
        publisher: "Mojang",
        features: "З мультиплеєром",
    },
    {
        price: 2299,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/84704087.jpg",
        name: "Cyberpunk 2077 для PS4 (Blu-ray диск, Russian version)",
        platform: "PlayStation 4",
        localizetion: "Російська версія",
        release: "19 листопада 2020 року",
        discType: "Blu-ray",
        releaseUkr: "19 листопада 2020 року",
        genre: "Action Рольові (RPG)",
        systemRequirements:
            "platform PlayStation 4 За наявності багатокористувацького мережевого режиму гри через Інтернет, потрібна передплата PlayStation Plus (купується окремо) і під'єднання ігрової консолі до мережі Інтернет",
        box: "Blu-ray box",
        developer: "CD Projekt Red",
        publisher: "CD Projekt RED",
        features: "Без мультиплеєра",
        developCountry: "Австрія",
        brendFrom: "США Японія",
    },
    {
        price: 2999,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/278863790.jpg",
        name: "The Elder Scrolls V: Skyrim для Nintendo Switch (Картридж, English version) (1014264)",
        platform: "Nintendo Switch",
        localizetion: "Англійська версія",
        discType: "Картридж",
        genre: "Рольові (RPG)",
        box: "Nintendo Switch Cartridge Case",
        features: "Без мультиплеєра",
        developCountry: "США",
        brendFrom: "США",
    },
    {
        price: 2999,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/278863747.jpg",
        name: "Bayonetta & Bayonetta 2 для Nintendo Switch (Картридж, English version) (1081229)",
        platform: "Nintendo Switch",
        localizetion: "Англійська версія",
        discType: "Картридж",
        genre: "Action",
        box: "Nintendo Switch Cartridge Case",
        features: "Без мультиплеєра",
        developCountry: "Японія",
        brendFrom: "Японія",
    },
    {
        price: 2549,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/180321747.jpg",
        name: "Immortals Fenyx Rising для Switch (Картридж, Russian version)",
        platform: "Nintendo Switch",
        localizetion: "Російська версія",
        discType: "Картридж",
        genre: "Action",
        box: "Nintendo Switch Cartridge Case",
        developer: "Ubisoft Entertainment",
        pg: 12,
        publisher: "Ubisoft Entertainment",
        developCountry: "Австрія",
        brendFrom: "Франція",
    },
    {
        price: 2999,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/231967092.jpg",
        name: "Super Smash Bros. Ultimate для Nintendo Switch (Картридж, English version) (45496422929)",
        platform: "Nintendo Switch",
        localizetion: "Англійська версія",
        discType: "Картридж",
        genre: "Пригоди (adventure)",
        box: "Nintendo Switch Cartridge Case",
        developCountry: "Японія",
        brendFrom: "Японія",
    },
    {
        price: 2499,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/274627293.jpg",
        name: "Diablo III: Eternal Collection для Nintendo Switch (Картридж, Russian version) (5030917259012)",
        platform: "Nintendo Switch",
        localizetion: "Англійська версія Російська версія",
        discType: "Картридж",
        playersNum: "1",
        genre: "Рольові (RPG)",
        box: "Nintendo Switch Cartridge Case",
        developer: "Blizzard Entertainment",
        pg: 18,
        publisher: "Blizzard Entertainment",
        features: "З мультиплеєром",
        developCountry: "США",
        brendFrom: "США",
    },
    {
        price: 2999,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/231972099.jpg",
        name: "Metroid Dread для Nintendo Switch (Картридж, English version) (45496428440/045496428464)",
        platform: "Nintendo Switch",
        localizetion: "Англійська версія",
        discType: "Картридж",
        genre: "Пригоди (adventure)",
        box: "Nintendo Switch Cartridge Case",
        developCountry: "Японія",
        brendFrom: "Японія",
    },
    {
        price: 949,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/74559654.jpg",
        name: "Mafia Trilogy для XBOX One (Blu-ray диск, Russian version)",
        platform: "Xbox One",
        release: "25 вересня 2020 року",
        discType: "Blu-ray",
        releaseUkr: "25 вересня 2020 року",
        genre: "Action",
        box: "Blu-ray box",
        developer: "2K Australia",
        publisher: "2K Games",
        features: "Без мультиплеєра",
        developCountry: "Австрія",
    },
    {
        price: 1999,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/219408772.jpg",
        name: "Life is Strange True Colors для Xbox One, Xbox Series X (Blu-ray-диск, English version/Russian subtitles)",
        platform: "Xbox One Xbox Series",
        distributorInUkraine: "ERC",
        localizetion: "Англійська версія З російськими субтитрами",
        release: "10 вересня 2021 року",
        discType: "Blu-ray",
        releaseUkr: "10 вересня 2021 року",
        playersNum: "1",
        genre: "Пригоди (adventure)",
        box: "Blu-ray box",
        servicActiv: "Не вимагає активації",
        developer: "Deck Nine",
        pg: 18,
        publisher: "Square Enix",
        features: "Без під'єднання до інтернету",
        developCountry: "Австрія",
        brendFrom: "Японія",
    },
    {
        price: 435,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/295427374.jpg",
        name: "Характеристики Ключ активації NARUTO SHIPPUDEN: Ultimate Ninja STORM 4 Road to Boruto для Xbox One/Series",
        platform: "Xbox One Xbox Series",
        localizetion: "Російська версія",
        discType: "Електронний ключ",
        genre: "Action Військові (fighting) Пригоди (adventure)",
        developer: "CyberConnect2",
        publisher: "Microsoft",
        developCountry: "США",
        brendFrom: "США",
    },
    {
        price: 579,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/186424695.jpg",
        name: "Характеристики Ключ активації Kingdom Come: Deliverance - Royal Edition для Xbox One/Series",
        platform: "Xbox One",
        localizetion: "Російська версія",
        genre: "Action Рольові (RPG)",
        developer: "Warhorse Studios",
        publisher: "Microsoft",
        developCountry: "США",
        brendFrom: "США",
    },
    {
        price: 343,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/176298432.jpg",
        name: "Характеристики Ключ активації RESIDENT EVIL 2: REMAKE для Xbox One/Series",
        platform: "Xbox One",
        localizetion: "Російська версія",
        discType: "Електронний ключ",
        genre: "Action Військові (fighting) Жахи, виживання (survival horror) Пригоди (adventure) Рольові (RPG) Симулятор Стратегії Шутер від першої особи (FPS)",
        developer: "Capcom Entertainment",
        publisher: "Microsoft",
        features: "З мультиплеєром",
        developCountry: "США",
        brendFrom: "США",
    },
    {
        price: 765,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/182317957.jpg",
        name: "Характеристики Ключ активації Sekiro: Shadows Die Twice - GOTY Edition (Секіро видання - Гра року) для Xbox One/Series",
        platform: "Xbox One",
        localizetion: "Російська версія",
        discType: "Електронний ключ",
        genre: "Action",
        developer: "From Software",
        publisher: "Microsoft",
        developCountry: "США",
        brendFrom: "США",
    },
    {
        price: 449,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/176299500.jpg",
        name: "Характеристики Ключ активації SpongeBob SquarePants: Battle for Bikini Bottom для Xbox One/Series",
        platform: "Xbox One",
        localizetion: "Російська версія",
        genre: "Дитячі Пригоди (adventure)",
        developer: "Bandai Namco",
        publisher: "Microsoft",
        features: "З мультиплеєром",
        developCountry: "США",
        brendFrom: "США",
    },
    {
        price: 289,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/19118057.jpg",
        name: "Характеристики Deus Ex Mankind Divided Collectors Edition (Xbox One, російська версія)",
        platform: "Xbox One Xbox Series",
        localizetion: "Російська версія",
        genre: "Рольові (RPG)",
        publisher: "Square Enix",
    },
    {
        price: 499,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/6930862.jpg",
        name: "Total War: Rome II – Emperor Edition для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "02 сентября 2013",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows XP/Vista/7/8, Процессор: Intel Dual Core 2GHz/Intel Single Core 2.6GHz, Оперативная память: 2 GB, Видеокарта: 512 MB, с поддержкой DirectX 9.0c, Место на диске: 35 G",
        genre: "Стратегії",
        systemRequirements:
            "ОС: Windows 7, Windows 8, Процессор: Intel Core i5, Оперативная память: 4 GB, Видеокарта: 1024 MB, с поддержкой DirectX 11, Место на диске: 35 GB",
        servicActiv: "Steam",
        developer: "Creative Assembly",
    },
    {
        price: 299,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/203607313.jpg",
        name: "The Walking Dead: The Telltale Definitive Series для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "29 октября 2020",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows 7 SP1 (64-разрядная), Процессор: Intel Core 2 Duo с тактовой частотой 2,8 ГГц, ОЗУ: 3 ГБ, Видеокарта: 2 ГБ, DirectX: Версии 11, Место на диске: 45 ГБ, Дополнительно: Требуются 64-разрядные процессор и операционная система",
        genre: "Пригоди (adventure)",
        systemRequirements:
            "ОС: Windows 7 SP1 (64-разрядная), Процессор: Intel Core i5-2500K, ОЗУ: 3 ГБ, Видеокарта: Nvidia GeForce GTX 960, DirectX: Версии 11, Место на диске: 45 ГБ, Дополнительно: Требуются 64-разрядные процессор и операционная система",
        developer: "Telltale Games",
    },
    {
        price: 999,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/6946405.jpg",
        name: "DOOM Eternal – Deluxe Edition для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "20 марта 2020",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows 7/10 (64-bit), Процессор: Intel Core i5 3.3 GHz, или AMD Ryzen 3 3.1 GHz, Оперативная память: 8 GB, Видеокарта: NVIDIA GeForce GTX 1050Ti или AMD Radeon R9 280, Место на диске: 50 GB",
        genre: "Action",
        systemRequirements:
            "ОС: Windows 10 (64-bit), Процессор: Intel Core i7-6700K, или AMD Ryzen 7 1800X, Оперативная память: 8 GB, Видеокарта: NVIDIA GeForce GTX 1060 (6GB), NVIDIA GeForce 970 (4GB), AMD RX 480 (8GB), Место на диске: 50 GB",
        servicActiv: "Steam",
        developer: "id Software",
        features: "З мультиплеєром",
    },
    {
        price: 149,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/6930474.jpg",
        name: "Dishonored для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Англійська версія",
        release: "12 октября 2012",
        discType: "Електронний ключ",
        minRequireSis:
            "OC: Windows Vista/Windows 7, Процессор: Двухъядерный 3,0 ГГц или выше, Оперативная память: 3ГБ, Жесткий диск: 9ГБ, Видеокарта: С 512 МБ, совместимая с DirectX 9 (NVIDIA GeForce GTX 460/ATI Radeon HD 5850), Звуковая карта: Совместимая с Windows",
        genre: "Action",
        systemRequirements:
            "OC: Windows Vista/Windows 7 (x64), Процессор: Четырехъядерный 2,4 ГГц, Оперативная память: 4ГБ, Жесткий диск: 9ГБ, Видеокарта: С 768 МБ, совместимая с DirectX 9 (NVIDIA GeForce GTX 460/ATI Radeon HD 5850), Звуковая карта: Совместимая с Windows",
        servicActiv: "Steam",
        developer: "Arkane Studios",
    },
    {
        price: 149,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/6931101.jpg",
        name: "Bulletstorm: Full Clip Edition для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "07 апреля 2017",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows 7/8/8.1/10 x64, Процессор: AMD A8-3850, Оперативная память: 6ГБ, Видеокарта: Radeon HD 6850, DirectX: Версии 11, Место на диске: 15ГБ",
        genre: "Action Пригоди (adventure)",
        systemRequirements:
            "ОС: Windows 7/8/8.1/10 x64, Процессор: Intel Core i5-760/AMD Athlon II X4 645 AM3, Оперативная память: 8ГБ, Видеокарта: GeForce GTX 750 Ti/Radeon HD 7770, DirectX: Версии 11, Место на диске: 15ГБ",
        servicActiv: "Steam",
        developer: "People Can Fly",
        publisher: "People Can Fly",
    },
    {
        price: 689,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/179786958.jpg",
        name: "Days Gone для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "18 мая 2021",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows 10 (64-разрядная), Процессор: Intel Core i5-2500K (3,3 ГГц) или AMD FX 6300 (3,5 ГГц), Оперативная память: 8 Гб, Видеокарта: Nvidia GeForce GTX 780 (3 Гб) или AMD Radeon R9 290 (4 Гб), DirectX: 11, Место на диске: 70 Гб",
        genre: "Action Пригоди (adventure)",
        systemRequirements:
            "ОС: Windows 10 (64-разрядная), Процессор: Intel Core i7-4770K (3,5 ГГц) или Ryzen 5 1500X (3,5 ГГц), Оперативная память: 16 Гб, Видеокарта: Nvidia GeForce GTX 1060 (6 Гб) или AMD Radeon RX 580 (8 Гб), DirectX: 11, Место на диске: 70 Гб",
        developer: "Bend Studio",
    },
    {
        price: 199,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/6941472.jpg",
        name: "ReCore: Definitive Edition для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "14 сентября 2018",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows 10 Version 14393.98 или выше required, Процессор: Intel Core i5 3550 3.3 GHz или AMD FX-6300, Оперативная память: 8 GB, Видеокарта: AMD Radeon R7 370 или NVIDIA GeForce GTX 660/570, Место на диске: 18 GB",
        genre: "Action Пригоди (adventure)",
        systemRequirements:
            "ОС: Windows 10 Version 14393.98 или выше required, Процессор: Intel Core i5 4570 3.2 GHz или AMD FX - 8350, Оперативная память: 16 GB, Видеокарта: AMD Radeon R9 290X или NVIDIA GeForce GTX 780, Место на диске: 18 GB",
        servicActiv: "Steam",
    },
    {
        price: 549,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/6930117.jpg",
        name: "Metro Exodus – Gold Edition для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "15 февраля 2019",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows 7/8/10 x64, Процессор: Intel Core i5-4440 или аналогичный, Оперативная память: 8ГБ, Видеокарта: GeForce GTX 670/GeForce GTX 1050/AMD Radeon HD 7870 (DirectX 11), Место на диске: 59ГБ, Дополнительно: 1080p, 30 fps",
        genre: "Action",
        systemRequirements:
            "ОС: Windows 10 x64, Процессор: Intel Core i7-4770k или аналогичный, Оперативная память: 8ГБ, Видеокарта: GeForce GTX 1070/GeForce RTX 2060/AMD RX VEGA 56 (DirectX 12), Место на диске: 59ГБ, Дополнительно: 1080p, 60 fps",
        servicActiv: "Steam",
        developer: "4A Games",
    },
    {
        price: 399,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/6942890.jpg",
        name: "Conan Exiles для ПК (Ключ активації Steam)",
        platform: "PC",
        localizetion: "Російська версія",
        release: "08 мая 2018",
        discType: "Електронний ключ",
        minRequireSis:
            "ОС: Windows 7, Windows 8, Windows 10 x64, Процессор: Intel Quad Core i5-2300 или AMD FX-6300, Оперативная память: 6ГБ, Видеокарта: GeForce GTX 560 (1ГБ), AMD Radeon HD 7770 (1ГБ), Место на диске: 50ГБ",
        genre: "Action Стратегії",
        systemRequirements:
            "ОС: Windows 7, Windows 8, Windows 10 x64, Процессор: Intel Quad Core i7 3770K или AMD Ryzen 7 1600X, Оперативная память: 8ГБ, Видеокарта: Nvidia GeForce GTX 780 Ti/970 или AMD R9 290/AMD RX480, Место на диске: 50ГБ",
        servicActiv: "Steam",
        developer: "Funcom",
        features: "З мультиплеєром",
    },
    {
        price: 599,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/29627495.jpg",
        name: "Rise of the Tomb Raider для PS4 (Blu-ray диск, Russian version)",
        platform: "PlayStation 4",
        localizetion: "Російська версія",
        release: "31.10.2016",
        discType: "Blu-ray",
        genre: "Пригоди (adventure)",
        systemRequirements:
            "platform PlayStation 4 За наявності багатокористувацького мережевого режиму гри через Інтернет, потрібна передплата PlayStation Plus (купується окремо) і під'єднання ігрової консолі до мережі Інтернет.",
        box: "Case Set",
        developer: "Square Enix",
        publisher: "Бука",
        features: "Без мультиплеєра",
        developCountry: "Австрія",
        brendFrom: "Японія",
    },
    {
        price: 2999,
        imgUrl: "https://content.rozetka.com.ua/goods/images/big_tile/304771419.jpg",
        name: "The Callisto Protocol Day One Edition для PS4 (Blu-ray диск, Russian subtitles)",
        platform: "PlayStation 4",
        localizetion: "З російськими субтитрами",
        release: "8 ноября 2019 г",
        discType: "Blu-ray",
        releaseUkr: "03.12.22",
        playersNum: "1",
        minRequireSis:
            "platform PlayStation 4 При наличии многопользовательского сетевого режима игры через Интернет, потребуется подписка PlayStation Plus (приобретается отдельно) и подключение игровой консоли к сети Интернет.",
        genre: "Action Жахи, виживання (survival horror)",
        box: "Blu-ray box",
        developer: "Striking Distance Studios",
        pg: 18,
        publisher: "Krafton",
        features: "Без мультиплеєра",
        developCountry: "Республіка Корея (Південна Корея)",
        brendFrom: "Республіка Корея (Південна Корея)",
    },
    {
        price: 93,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/264898742.jpg",
        name: "Характеристики LEGO Ninjago Movie Videogame (PS4, російські субтитри)",
        platform: "PlayStation 4",
        localizetion: "З російськими субтитрами",
        genre: "Дитячі Пригоди (adventure)",
        publisher: "Warner Bros. Games",
    },
    {
        price: 117,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/90135312.jpg",
        name: "Характеристики Lego Harry Potter Collection (Sony PlayStation 4 ,Англійська версія)",
        platform: "PlayStation 4",
        localizetion: "Англійська версія",
        discType: "Blu-ray",
        developer: "Warner Bros. Interactive Entertainment",
        features: "Без мультиплеєра",
    },
    {
        price: 96,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/22551271.jpg",
        name: "Характеристики Mad Max (PS4, російські субтитри)",
        platform: "PlayStation 4",
        localizetion: "З російськими субтитрами",
        genre: "Автосимулятори (гонки)",
        publisher: "Warner Bros. Games",
    },
    {
        price: 82,
        imgUrl: "https://content1.rozetka.com.ua/goods/images/big_tile/180717481.jpg",
        name: "Характеристики Assassins Creed Unity (PS4, російська версія)",
        platform: "PlayStation 4",
        localizetion: "Російська версія",
        genre: "Пригоди (adventure)",
        developer: "Ubisoft Entertainment",
        publisher: "Ubisoft Entertainment",
    },
    {
        price: 86,
        imgUrl: "https://content2.rozetka.com.ua/goods/images/big_tile/19117557.jpg",
        name: "Характеристики NieR Automata Game of the YoRHa Edition (PS4)",
        platform: "PlayStation 4",
        localizetion: "Англійська версія",
        genre: "Рольові (RPG)",
        publisher: "Square Enix",
    },
];

const set = new Set([]);

const arr2 = arr.forEach((el) => {
    Object.keys(el).forEach((el) => set.add(el));
});

console.log(Array.from(set));
